---
title: "Analysis of Acclimated P-Model Setups"
date: "`r Sys.Date()`"
author: "Pascal Schneider"
output:
  rmdformats::downcute:
    code_folding: hide
    lightbox: true
    gallery: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	error = FALSE,
	message = FALSE,
	warning = FALSE,
	cache = TRUE
)
suppressMessages(source("~/projects/mscthesis/scripts/final/source_fct_pkg.R"))
```


# Sanity check with rsofun output
```{r}
## Getting driver and evaluation data
load("~/data/rsofun_benchmarking/df_drivers_topt_v3.4.Rdata")
df_drivers_k19     <- df_drivers_topt
df_evaluation_k19  <- readRDS("~/data/mscthesis/final/df_obs_opt_postQC.rds")


## Run acclimated P-Model
settings <- get_settings()
df_accl  <- run_rpmodel_accl(settings = settings, df_drivers = df_drivers_k19, df_evaluation = df_evaluation_k19, target_var = target_var)


## Select variables from acclimated rsofun
vars_ <- c("vcmax", "jmax", "vcmax25", "jmax25", "tc_growth_air", "kphio", "xi") # "vcmax", "jmax", "vcmax25", "jmax25", "tc_growth_air", "kphio", "xi"
df_rsof <- df_accl %>%
    dplyr::select(sitename, date) %>% 
    left_join(readRDS("~/data/mscthesis/final/rsofun_v3.4_topt_k19_tau30.rds") %>% unnest(data)) %>% 
    dplyr::select(sitename, date, vcmax, jmax, vcmax25, jmax25, debug1, debug2) %>% 
    rename(tc_growth_air = debug1,
           kphio         = debug2) %>% 
    pivot_longer(cols = any_of(vars_), names_to = "variable", values_to = "rsofun")


## Select variables from acclimated rpmodel
df_rpm <- df_accl %>%
    unnest(c(rpm_accl, forcing)) %>% 
    dplyr::select(sitename, date, vcmax, jmax, vcmax25, jmax25, tc_growth_air, kphio) %>% 
    pivot_longer(cols = any_of(vars_), names_to = "variable", values_to = "rpmodel")

    
## Connect and plot both data frames
left_join(df_rsof, df_rpm) %>% 
    dplyr::filter(variable != "jmax",
                  variable != "vcmax",) %>%
    ggplot() +
    aes(x = rsofun, y = rpmodel) +
    geom_abline() +
    geom_point() +
    geom_smooth(method = "lm") +
    facet_wrap( ~ variable, scales = "free", ncol = 2) +
    ggpmisc::stat_poly_eq(formula = y ~ x,
                          aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")),
                          parse = TRUE)
```


# Analytical vs. numerical
## Get driver and evaluation data
```{r}
df_drivers_p21    <- readRDS("~/data/mscthesis/final/df_drivers_p21.rds")
df_evaluation_p21 <- readRDS("~/data/mscthesis/raw/leaf_traits_peng2021/df_P21_clean.rds") %>%
    dplyr::select(-author) %>%
    rename_with(tolower) %>%
    dplyr::filter(!((is.na(jmax) | is.na(vcmax))),
                  !is.na(date),
                  !is.na(lat),
                  !is.na(lon)) %>%
    group_by(site, date) %>%
    nest() %>%
    ungroup() %>%
    rename(sitename = site,
           data_raw = data)
```

## Smith37
```{r fig.height=6, fig.width=8}
## Analytical
settings <- get_settings()
df_ana_s37   <- run_rpmodel_accl(settings = settings, df_drivers = df_drivers_p21, df_evaluation = df_evaluation_p21) %>% get_instant_vcmax_jmax()
p_ana_s37    <- plot_two_long_df(df_x = make_long_df(df_in = df_ana_s37, dataset = "analytical_s37"), df_x_dataset = "analytical_s37", df_y = make_df_evaluation_p21_long(df_in = df_ana_s37), df_y_dataset = "peng21")
    

## Numerical
settings <- get_settings()
settings$rpmodel_accl$method_optim   <- "numerical"
df_num_s37 <- run_rpmodel_accl(settings = settings, df_drivers = df_drivers_p21, df_evaluation = df_evaluation_p21) %>% get_instant_vcmax_jmax(ftemp_method = settings$rpmodel_accl$method_ftemp)
p_num_s37  <- plot_two_long_df(df_x = make_long_df(df_in = df_num_s37, dataset = "numerical_s37"), df_x_dataset = "numerical_s37", df_y = make_df_evaluation_p21_long(df_in = df_num_s37), df_y_dataset = "peng21")


## Plots
p1 <- p_ana_s37 + xlim(0, 10e-4) + ylim(0, 10e-4)
p2 <- p_num_s37 + xlim(0, 10e-4) + ylim(0, 10e-4)

p1/p2
```


## Farquhar89
```{r fig.height=6, fig.width=8}
## Analytical
settings <- get_settings()
settings$rpmodel_accl$method_jmaxlim <- "farquhar89"
df_ana_f89   <- run_rpmodel_accl(settings = settings, df_drivers = df_drivers_p21, df_evaluation = df_evaluation_p21) %>% get_instant_vcmax_jmax()
p_ana_f89    <- plot_two_long_df(df_x = make_long_df(df_in = df_ana_f89, dataset = "analytical_f89"), df_x_dataset = "analytical_f89", df_y = make_df_evaluation_p21_long(df_in = df_ana_f89), df_y_dataset = "peng21")
    

## Numerical
settings <- get_settings()
settings$rpmodel_accl$method_jmaxlim <- "farquhar89"
settings$rpmodel_accl$method_optim <- "numerical"
df_num_f89 <- run_rpmodel_accl(settings = settings, df_drivers = df_drivers_p21, df_evaluation = df_evaluation_p21) %>% get_instant_vcmax_jmax(ftemp_method = settings$rpmodel_accl$method_ftemp)
p_num_f89  <- plot_two_long_df(df_x = make_long_df(df_in = df_num_f89, dataset = "numerical_f89"), df_x_dataset = "numerical_f89", df_y = make_df_evaluation_p21_long(df_in = df_num_f89), df_y_dataset = "peng21")


## Plots
p1 <- p_ana_f89 + xlim(0, 10e-4) + ylim(0, 10e-4)
p2 <- p_num_f89 + xlim(0, 10e-4) + ylim(0, 10e-4)

p1 / p2
```


## Leaf energy balance + computing time
```{r}
## Analytical
settings <- get_settings()
t_start <- Sys.time()
df_dummy <- run_rpmodel_accl(settings = settings, df_drivers = df_drivers_p21, df_evaluation = df_evaluation_p21) %>% get_instant_vcmax_jmax(ftemp_method = settings$rpmodel_accl$method_ftemp)
t_ana <- difftime(Sys.time(), t_start, units = "min") %>% round(2)


## Numerical, no EB
settings$rpmodel_accl$method_optim <- "numerical"
t_start <- Sys.time()
df_noeb <- run_rpmodel_accl(settings = settings, df_drivers = df_drivers_p21, df_evaluation = df_evaluation_p21) %>% get_instant_vcmax_jmax(ftemp_method = settings$rpmodel_accl$method_ftemp)
t_noeb <- difftime(Sys.time(), t_start, units = "min") %>% round(2)
p_noeb  <- plot_two_long_df(df_x = make_long_df(df_in = df_noeb, dataset = "no_energy_balance"), df_x_dataset = "no_energy_balance", df_y = make_df_evaluation_p21_long(df_in = df_noeb), df_y_dataset = "peng21")


## EB via plantecophys
settings$rpmodel_accl$method_eb <- "plantecophys"
t_start <- Sys.time()
df_eb_pl <- run_rpmodel_accl(settings = settings, df_drivers = df_drivers_p21, df_evaluation = df_evaluation_p21) %>% get_instant_vcmax_jmax(ftemp_method = settings$rpmodel_accl$method_ftemp)
t_eb_pl <- difftime(Sys.time(), t_start, units = "min") %>% round(2)
p_eb_pl  <- plot_two_long_df(df_x = make_long_df(df_in = df_eb_pl, dataset = "eb_plantecophys"), df_x_dataset = "eb_plantecophys", df_y = make_df_evaluation_p21_long(df_in = df_eb_pl), df_y_dataset = "peng21")


## EB via tealeaves
t_start <- Sys.time()
settings$rpmodel_accl$method_eb <- "tealeaves"
t_start <- Sys.time()
df_eb_te <- run_rpmodel_accl(settings = settings, df_drivers = df_drivers_p21, df_evaluation = df_evaluation_p21) %>% get_instant_vcmax_jmax(ftemp_method = settings$rpmodel_accl$method_ftemp)
t_eb_te <- difftime(Sys.time(), t_start, units = "min") %>% round(2)
p_eb_te  <- plot_two_long_df(df_x = make_long_df(df_in = df_eb_te, dataset = "eb_tealeaves"), df_x_dataset = "eb_tealeaves", df_y = make_df_evaluation_p21_long(df_in = df_eb_te), df_y_dataset = "peng21")


## Computing time (run in console directly is quicker than in chunk!)
cat(" Computation time: \n",
    "_______________________________ \n",
    "Analytical Model:      ", ifelse(t_ana > 1, paste0(t_ana, " min"), paste0(t_ana*60, " sec")), "\n",
    "Numerical Model:       ", ifelse(t_noeb > 1, paste0(t_noeb, " min"), paste0(t_noeb*60, " sec")), "\n",
    "Num. + Planteco Model: ", ifelse(t_eb_pl > 1, paste0(t_eb_pl, " min"), paste0(t_eb_pl*60, " sec")), "\n",
    "Num. + tealeaves Model:", ifelse(t_eb_te > 1, paste0(t_eb_te, " min"), paste0(t_eb_te*60, " sec")), "\n")



## Plots
p_noeb + xlim(0, 6e-4) + ylim(0, 6e-4)
p_eb_pl + xlim(0, 6e-4) + ylim(0, 6e-4)
p_eb_te + xlim(0, 6e-4) + ylim(0, 6e-4)
```


# Analysis of s37 + numeric
## Kattge07 vs. Kumarathunge19
```{r}
## Kumarathunge19
settings <- get_settings()
settings$rpmodel_accl$method_optim <- "numerical"
df_k19 <- run_rpmodel_accl(settings = settings, df_drivers = df_drivers_p21, df_evaluation = df_evaluation_p21) %>% get_instant_vcmax_jmax(ftemp_method = settings$rpmodel_accl$method_ftemp)
p_k19  <- plot_two_long_df(df_x = make_long_df(df_in = df_k19, dataset = "kumarathunge19"), df_x_dataset = "kumarathunge19", df_y = make_df_evaluation_p21_long(df_in = df_k19), df_y_dataset = "peng21")


## Kattge07
settings$rpmodel_accl$method_ftemp <- "kattge07"
df_k07 <- run_rpmodel_accl(settings = settings, df_drivers = df_drivers_p21, df_evaluation = df_evaluation_p21) %>% get_instant_vcmax_jmax(ftemp_method = settings$rpmodel_accl$method_ftemp)
p_k07  <- plot_two_long_df(df_x = make_long_df(df_in = df_k07, dataset = "kattge07"), df_x_dataset = "kattge07", df_y = make_df_evaluation_p21_long(df_in = df_k07), df_y_dataset = "peng21")


## Plots
p_k19 + xlim(0, 6e-4) + ylim(0, 6e-4)
p_k07 + xlim(0, 6e-4) + ylim(0, 6e-4)
```


## Acclimation time-spans
```{r}
## Reference: All tau = 30:
settings <- get_settings()
settings$rpmodel_accl$method_optim <- "numerical"
df_all_30 <- run_rpmodel_accl(settings = settings, df_drivers = df_drivers_p21, df_evaluation = df_evaluation_p21) %>% get_instant_vcmax_jmax(ftemp_method = settings$rpmodel_accl$method_ftemp)
p_all_30  <- plot_two_long_df(df_x = make_long_df(df_in = df_all_30, dataset = "all_tau_30"), df_x_dataset = "all_tau_30", df_y = make_df_evaluation_p21_long(df_in = df_all_30), df_y_dataset = "peng21")


## Shorter thermal acclimation: tc_air_tau = 10:
settings$rpmodel_accl$tau$tc_air <- 45
df_temp10 <- run_rpmodel_accl(settings = settings, df_drivers = df_drivers_p21, df_evaluation = df_evaluation_p21) %>% get_instant_vcmax_jmax(ftemp_method = settings$rpmodel_accl$method_ftemp)
p_temp10  <- plot_two_long_df(df_x = make_long_df(df_in = df_temp10, dataset = "temp_tau_10"), df_x_dataset = "temp_tau_10", df_y = make_df_evaluation_p21_long(df_in = df_temp10), df_y_dataset = "peng21")


## Shorter light acclimation: ppfd_tau = 10:
settings$rpmodel_accl$tau$tc_air <- 30
settings$rpmodel_accl$tau$ppfd   <- 10
df_ppfd10 <- run_rpmodel_accl(settings = settings, df_drivers = df_drivers_p21, df_evaluation = df_evaluation_p21) %>% get_instant_vcmax_jmax(ftemp_method = settings$rpmodel_accl$method_ftemp)
p_ppfd10  <- plot_two_long_df(df_x = make_long_df(df_in = df_ppfd10, dataset = "ppfd_tau_10"), df_x_dataset = "ppfd_tau_10", df_y = make_df_evaluation_p21_long(df_in = df_ppfd10), df_y_dataset = "peng21")


## Shorter thermal & light acclimation: temp_tau = ppfd_tau = 10:
settings$rpmodel_accl$tau$tc_air <- 10
df_tempppfd30 <- run_rpmodel_accl(settings = settings, df_drivers = df_drivers_p21, df_evaluation = df_evaluation_p21) %>% get_instant_vcmax_jmax(ftemp_method = settings$rpmodel_accl$method_ftemp)
p_tempppfd30  <- plot_two_long_df(df_x = make_long_df(df_in = df_tempppfd30, dataset = "temp_ppfd_tau_10"), df_x_dataset = "temp_ppfd_tau_10", df_y = make_df_evaluation_p21_long(df_in = df_tempppfd30), df_y_dataset = "peng21")


## Plots
p_all_30 + xlim(0, 4e-4) + ylim(0, 4e-4)
p_temp10 + xlim(0, 4e-4) + ylim(0, 4e-4)
p_ppfd10 + xlim(0, 4e-4) + ylim(0, 4e-4)
p_tempppfd30 + xlim(0, 4e-4) + ylim(0, 4e-4)


## Notes
# tc_air tau = 5 -> r'2 0.54
# tc_air tau = 15 -> r'2 0.48
# tc_air tau = 45 -> r'2 0.68

```



# Final Model
```{r}
## Best model:
settings <- get_settings()
settings$rpmodel_accl$method_optim <- "numerical"
settings$rpmodel_accl$method_eb <- "tealeaves"
settings$rpmodel_accl$tau$tc_air <- 5


t_start <- Sys.time()
df_best <- run_rpmodel_accl(settings = settings, df_drivers = df_drivers_p21, df_evaluation = df_evaluation_p21) %>% get_instant_vcmax_jmax(ftemp_method = settings$rpmodel_accl$method_ftemp)
p_best  <- plot_two_long_df(df_x = make_long_df(df_in = df_best, dataset = "num_s37_planteco_temp10"), df_x_dataset = "num_s37_planteco_temp10", df_y = make_df_evaluation_p21_long(df_in = df_best), df_y_dataset = "peng21")
t_dur   <- Sys.time() - t_start


t_dur
p_best
```



# ---
## Testing Bias
```{r}
bias_s37 <- left_join(p_ana_s37$data, df_drivers_p21 %>%
                          dplyr::select(sitename, forcing) %>% 
                          unnest(forcing)) %>% 
    dplyr::filter(variable == "vcmax") %>% 
    mutate(bias = (x-y)/y*100) 

bias_s37 %>% 
    pivot_longer(cols = c(patm, vpd, co2, elv, tc_growth_leaf, tc_home, ppfd, doy), names_to = "var", values_to = "val") %>% 
    ggplot() +
    aes(x = val, y = bias) +
    geom_point() +
    geom_smooth(method = "lm") +
    geom_abline(slope = 0, intecept = 0) +
    facet_wrap(~var, scales = "free_x") +
    ylim(-250, 250)
```



## Testzone
```{r}
## Get data
df_drivers_p21    <- readRDS("~/data/mscthesis/final/df_drivers_p21.rds")
df_evaluation_p21 <- readRDS("~/data/mscthesis/raw/leaf_traits_peng2021/df_P21_clean.rds") %>%
    dplyr::select(-author) %>%
    rename_with(tolower) %>%
    dplyr::filter(!((is.na(jmax) | is.na(vcmax))),
                  !is.na(date),
                  !is.na(lat),
                  !is.na(lon)) %>%
    group_by(site, date) %>%
    nest() %>%
    ungroup() %>%
    rename(sitename = site,
           data_raw = data)
```
