---
title: "Analysis of Numerical rpmodel"
date: "`r Sys.Date()`"
author: "Pascal Schneider"
output:
  rmdformats::downcute:
    code_folding: hide
    lightbox: true
    gallery: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	error = F,
	message = FALSE,
	warning = FALSE
)
suppressMessages(source("~/projects/mscthesis/scripts/final/source_fct_pkg.R"))
```

# Sanity Checks
## Environmental response
### Function definition
```{r, fig.height = 6, fig_width = 5}
rpmodel_env_response <- function(df_ref   = "no_input",
                                 settings = "no_input",
                                 targets  = "no_input",
                                 drivers  = "no_input",
                                 remove_non_convergence = F,
                                 scales_to_one          = T,
                                 p_output               = "per_target",
                                 df_full  = "no_input"){
    
    ## Input Check ####
    ## Environmental setup
    if (df_ref[1] == "no_input") {
        df_ref <- tibble(tc        = 25,
                         tc_home   = 20,
                         vpd       = 1000,
                         co2       = 400,
                         ppfd      = 1500e-6,
                         patm      = 101325,
                         nsteps    = 50)
    }
    
    
    ## rpmodel setup
    if (settings[1] == "no_input") {settings <- get_settings()}
    if (targets[1] == "no_input") {targets   <- c("chi", "vcmax", "jmax", "gs", "a_gross")} # , "vcmax25", "jmax25"
    if (drivers[1] == "no_input") {drivers   <- c("tc", "vpd", "co2", "ppfd", "patm")}
    
    
    ## Tibble building ####
    ## Environmental setup
    if (!(is_tibble(df_full))) {
        df_ana <- bind_rows(list =
                               tibble(
                                   tc = seq(from = 0, to = 40, length.out = df_ref$nsteps),
                                   tc_home   = rep(df_ref$tc_home, df_ref$nsteps),
                                   vpd       = rep(df_ref$vpd, df_ref$nsteps),
                                   co2       = rep(df_ref$co2, df_ref$nsteps),
                                   ppfd      = rep(df_ref$ppfd, df_ref$nsteps),
                                   patm      = rep(df_ref$patm, df_ref$nsteps),
                                   env_var   = "tc"),
                           tibble(
                                   tc        = rep(df_ref$tc, df_ref$nsteps),
                                   tc_home   = seq(from = 0, to = 40, length.out = df_ref$nsteps),
                                   vpd       = rep(df_ref$vpd, df_ref$nsteps),
                                   co2       = rep(df_ref$co2, df_ref$nsteps),
                                   ppfd      = rep(df_ref$ppfd, df_ref$nsteps),
                                   patm      = rep(df_ref$patm, df_ref$nsteps),
                                   env_var   = "tc_home"),
                           tibble(
                                   tc        = rep(df_ref$tc, df_ref$nsteps),
                                   tc_home   = rep(df_ref$tc_home, df_ref$nsteps),
                                   vpd       = seq(from = 200, to = 2000, length.out = df_ref$nsteps),
                                   co2       = rep(df_ref$co2, df_ref$nsteps),
                                   ppfd      = rep(df_ref$ppfd, df_ref$nsteps),
                                   patm      = rep(df_ref$patm, df_ref$nsteps),
                                   env_var   = "vpd"),
                           tibble(
                                   tc        = rep(df_ref$tc, df_ref$nsteps),
                                   tc_home   = rep(df_ref$tc_home, df_ref$nsteps),
                                   vpd       = rep(df_ref$vpd, df_ref$nsteps),
                                   co2       = seq(from = 200, to = 1000, length.out = df_ref$nsteps),
                                   ppfd      = rep(df_ref$ppfd, df_ref$nsteps),
                                   patm      = rep(df_ref$patm, df_ref$nsteps),
                                   env_var   = "co2"),
                           tibble(
                                   tc        = rep(df_ref$tc, df_ref$nsteps),
                                   tc_home   = rep(df_ref$tc_home, df_ref$nsteps),
                                   vpd       = rep(df_ref$vpd, df_ref$nsteps),
                                   co2       = rep(df_ref$co2, df_ref$nsteps),
                                   ppfd      = seq(from = 100e-6, to = 3000e-6, length.out = df_ref$nsteps),
                                   patm      = rep(df_ref$patm, df_ref$nsteps),
                                   env_var   = "ppfd"),
                           tibble(
                                   tc        = rep(df_ref$tc, df_ref$nsteps),
                                   tc_home   = rep(df_ref$tc_home, df_ref$nsteps),
                                   vpd       = rep(df_ref$vpd, df_ref$nsteps),
                                   co2       = rep(df_ref$co2, df_ref$nsteps),
                                   ppfd      = rep(df_ref$ppfd, df_ref$nsteps),
                                   patm      = seq(from = calc_patm(4000), to = calc_patm(0), length.out = df_ref$nsteps),
                                   env_var   = "patm"))
        
        
        ## Doubling tibble to compare analytical vs. numerical setup
        df_num       <- df_ana
        df_ana$setup <- "analytical"
        df_num$setup <- "numerical"
        df_full      <- bind_rows(list(df_ana, df_num))
        
        
        ## Running rpmodel ####
        for (row in 1:nrow(df_full)) {
            message('\014')
            message("Testing environmental response... ", round(row / nrow(df_full) * 100), " %")
            
            if (df_full$setup[row] == "analytical") {settings$rpmodel_accl$method_optim <- "analytical"}
            if (df_full$setup[row] == "numerical") {settings$rpmodel_accl$method_optim <- "numerical"}
            
            df_loop <- rpmodel(
              
              ## Acclimated inputs
              tc_growth_air = df_full$tc[row],
              tc_home       = df_full$tc_home[row],
              vpd           = df_full$vpd[row],
              co2           = df_full$co2[row],
              ppfd          = df_full$ppfd[row],
              patm          = df_full$patm[row],
              
              ## Local parameters
              kphio         = settings$rpmodel_accl$kphio_calib,
              apar_soilm    = settings$rpmodel_accl$apar_soilm_calib,
              bpar_soilm    = settings$rpmodel_accl$bpar_soilm_calib,
              
              ## Calculation methods
              method_optim   = settings$rpmodel_accl$method_optim, 
              method_jmaxlim = settings$rpmodel_accl$method_jmaxlim,
              method_ftemp   = settings$rpmodel_accl$method_ftemp,
              method_eb      = settings$rpmodel_accl$method_eb
              )
            
            ## Definition of rpmodel output
            df_full$chi[row]     <- df_loop$chi
            df_full$ci[row]      <- df_loop$ci
            df_full$xi[row]      <- df_loop$xi
            df_full$gs[row]      <- df_loop$gs
            df_full$vcmax[row]   <- df_loop$vcmax
            df_full$vcmax25[row] <- df_loop$vcmax25
            df_full$jmax[row]    <- df_loop$jmax
            df_full$jmax25[row]  <- df_loop$jmax25
            df_full$kphio[row]   <- df_loop$kphio
            df_full$a_gross[row] <- df_loop$a_gross
            df_full$tc_growth_leaf[row]   <- df_loop$tc_growth_leaf
            df_full$opt_convergence[row]   <- df_loop$opt_convergence
        }
    }
    
    ## Wrangling tibble for plotting
    df_temp <- df_full %>%
        mutate(env_var = as.factor(env_var),
               setup = as.factor(setup),
               setup = fct_relevel(setup, "numerical", "analytical"))
    
    if (remove_non_convergence) {
        df_temp <- df_temp %>% dplyr::filter(opt_convergence == 0 | is.na(opt_convergence))
        }
    

    ## Generating plots ####
    ## Create empty list
    p_all <- list()
    
    
    ## Loop and append plots
    if (p_output == "per_driver") {
            for (v in drivers) {
            
            
            ## Get reference value of driver
            vline <- df_ref[[v]]
            
            
            ## Rescale all target values to maximum across all env. conditions
            if (scales_to_one) {
                df_max <- tibble(max_val = NA, targets = NA)
                    
                for (t in targets) {
                    ## Take max value of currently looped env. variable
                    max_val <- df_temp %>% dplyr::filter(env_var == v) %>% dplyr::select(!!t) %>% max()
                    
                    ## Take max value across all env. variables
                    # max_val <- max(df_temp[t])
                    
                    ## Divide by max value
                    df_temp[, t] <- df_temp[t] / max_val
                    
                    ## Add x coodrinate for plotting
                    x  <- (min(df_temp[v]) + max(df_temp[v]))  / 2
                    x <- min(df_temp[v])
                    
                    ## Add all to df
                    df_max <- bind_rows(list(df_max, tibble(max_val = max_val, targets = t, x = x)))
                }
                df_max <- df_max %>%
                    drop_na() %>%
                    mutate(targets = as.factor(targets),
                           max_val = ifelse(max_val < 0.001, round(max_val*10^6, 2), round(max_val, 2)),
                           label   = paste0("Max.: ", max_val),
                           setup = "numerical")
            }
            
            
            ## Plotting
            p_append <- df_temp %>%
                dplyr::filter(env_var == v) %>%
                pivot_longer(cols = all_of(v), names_to = "driver", values_to = "driver_value") %>%
                pivot_longer(cols = c(targets), names_to = "targets", values_to = "targets_value") %>% 
                ggplot() +
                aes(x = driver_value, y = targets_value, color = setup, linetype = setup) +
                geom_vline(xintercept = vline, alpha = 0.5, color = "grey50", linetype = "solid", size = 0.5) +
                geom_point(size = 1.5, alpha = 0.8) +
                ylab(paste(" ")) +
                xlab(paste(v)) +
                facet_wrap(~targets, ncol = 3) +
                labs(title = paste0("Sensitivity to ", v),
                     caption = paste0("\n Reference conditions (vertical grey lines): \n",
                                      "tc = ", df_ref$tc, " °C",
                                      ", tc_home = ", df_ref$tc_home, " °C",
                                      ", vpd = ", df_ref$vpd, " Pa",
                                      ", co2 = ", df_ref$co2, " ppm",
                                      ", ppfd = ", df_ref$ppfd, " µmol/m2/s",
                                      ", patm = ", df_ref$patm, " Pa")) +
                  theme(plot.caption = element_text(hjust = 0.5, size = 10, lineheight = 1.1),
                        legend.position = c(0.825, 0.25))
            
            ## Fix yscale from 0 to 1 for comparisons:
            if (scales_to_one) {
                p_append <- p_append +
                    ylim(0, 1) +
                    ylab("Relative to maximum value") +
                    geom_text(data = df_max, aes(x = x, y = 0.1, label = label), colour = "black",
                              hjust = 0,
                              size = 4,
                              inherit.aes = FALSE, parse = FALSE)
            
            ## Append plot to list
            p_all[[length(p_all)+1]] <- p_append
            }
        }
    } else if (p_output == "per_target") {
        for (t in targets) {
            
            ## Plotting
            p_append <- df_temp %>%
                pivot_longer(cols = all_of(drivers), names_to = "driver", values_to = "driver_value") %>%
                pivot_longer(cols = all_of(t), names_to = "targets", values_to = "targets_value") %>% 
                dplyr::filter(targets == t,
                              driver  == env_var) %>%
                ggplot() +
                aes(x = driver_value, y = targets_value, color = setup, linetype = setup) +
                geom_vline(data = df_ref %>% pivot_longer(cols = all_of(drivers), names_to = "driver", values_to = "x"),
                           aes(xintercept = x),
                           alpha = 0.5, color = "grey50", linetype = "solid", size = 0.5) +
                geom_point(size = 1.5, alpha = 0.8) +
                xlab(paste(" ")) +
                ylab(paste(t)) +
                facet_wrap(~driver, ncol = 3, scales = "free_x") +
                labs(title = paste0("Sensitivity of ", t),
                     caption = paste0("\n Reference conditions (vertical grey lines): \n",
                                      "tc = ", df_ref$tc, " °C",
                                      ", tc_home = ", df_ref$tc_home, " °C",
                                      ", vpd = ", df_ref$vpd, " Pa",
                                      ", co2 = ", df_ref$co2, " ppm",
                                      ", ppfd = ", df_ref$ppfd, " µmol/m2/s",
                                      ", patm = ", df_ref$patm, " Pa")) +
                  theme(plot.caption = element_text(hjust = 0.5, size = 10, lineheight = 1.1),
                        legend.position = c(0.825, 0.25))
            
            ## Fixing scales form comparison
            if ( t == "chi")     {p_append <- p_append + ylim(0.25, 1)}
            if ( t == "vcmax")   {p_append <- p_append + ylim(0, 3e-4)}
            if ( t == "jmax")    {p_append <- p_append + ylim(0, 6e-4)}
            if ( t == "gs")      {p_append <- p_append + ylim(0, 8e-6)}
            if ( t == "a_gross") {p_append <- p_append + ylim(0, 7e-5)}
            
            ## Append plot to list
            p_all[[length(p_all)+1]] <- p_append
        }
    }
    
    ## Define output ####
    out <- list(plot = p_all,
                data = df_full)   
    
    return(out)
}
```

### Plotting
#### Smith37
```{r, fig.height = 6, fig_width = 5}
settings <- get_settings()
p_s37 <- rpmodel_env_response(settings = settings, df_full = p_s37$data)
p_s37$plot
```


#### Farquhar89
```{r, fig.height = 6, fig_width = 5}
settings <- get_settings()
settings$rpmodel_accl$method_jmaxlim <- "farquhar89"
p_f89 <- rpmodel_env_response(settings = settings, df_full = p_f89$data)
p_f89$plot
```


#### Smith37 + plantecophys eb
```{r, fig.height = 6, fig_width = 5}
settings <- get_settings()
settings$rpmodel_accl$method_eb <- "plantecophys"
p_s37_pl <- rpmodel_env_response(settings = settings, df_full = p_s37_pl$data)
p_s37_pl$plot
```

#### Smith37 + tealeaves eb
```{r, fig.height = 6, fig_width = 5}
settings <- get_settings()
settings$rpmodel_accl$method_eb <- "tealeaves"
p_s37_te <- rpmodel_env_response(settings = settings, df_full = p_s37_te$data)
p_s37_te$plot
```

## Cost function
```{r}
## Environmental conditions and respective optimal variables
(opt_vars <- calc_optimal_tcleaf_vcmax_jmax(tc_leaf = 25,
                                           patm = 101325,
                                           co2 = 400,
                                           vpd = 1000,
                                           ppfd = 130,
                                           fapar = 1,
                                           kphio = 0.05,
                                           beta = 146,
                                           c_cost = 0.41,
                                           vcmax_start = 20,
                                           gs_start = 0.5,
                                           jmax_start = 20,
                                           method_jmaxlim_inst = "smith37")$varlist)

vcmax_fix <- opt_vars$vcmax_mine * 3600*24
jmax_fix  <- opt_vars$jmax_mine  * 3600*24
gs_fix    <- opt_vars$gs_mine    * 3600*24


## Arrays to visualize plot dependencies
l_out   <- 100
lims    <- 10
vcmax_0 <- vcmax_fix
jmax_0  <- jmax_fix
gs_0    <- gs_fix

vcmax_v <- seq(0, vcmax_0*lims, length.out = l_out)
jmax_v  <- seq(0, jmax_0*lims, length.out = l_out)
gs_v    <- seq(0, gs_0*lims, length.out = l_out)
cost_3d  <- array (data = NA, dim=c(l_out,l_out,l_out))


## PLOTTING
cost_gg2d <- rep(NA, length(vcmax_v))
method_jmaxlim_inst <- "smith37"

df_2d <- tibble(
    cost_vcmax = cost_gg2d,
    cost_jmax  = cost_gg2d,
    cost_gs    = cost_gg2d,
    vcmax      = vcmax_v,
    jmax       = jmax_v,
    gs         = gs_v
)

## Free vcmax
for (i in 1:length(vcmax_v)) {
    df_2d$cost_vcmax[i] <- optimise_this_tcleaf_vcmax_jmax(
        par        = c(df_2d$vcmax[i], gs_fix, jmax_fix),
        args       = c(tc_leaf, patm, co2, vpd),
        iabs       = (ppfd * fapar),
        kphio      = kphio,
        method_jmaxlim_inst = method_jmaxlim_inst,
        maximize   = TRUE
    )
}


## Free jmax
for (i in 1:length(vcmax_v)) {
    df_2d$cost_jmax[i] <- optimise_this_tcleaf_vcmax_jmax(
        par        = c(vcmax_fix, gs_fix, df_2d$jmax[i]),
        args       = c(tc_leaf, patm, co2, vpd),
        iabs       = (ppfd * fapar),
        kphio      = kphio,
        method_jmaxlim_inst = method_jmaxlim_inst,
        maximize   = TRUE
    )
}


## Free gs
for (i in 1:length(vcmax_v)) {
    df_2d$cost_gs[i] <- optimise_this_tcleaf_vcmax_jmax(
        par        = c(vcmax_fix, df_2d$gs[i], jmax_fix),
        args       = c(tc_leaf, patm, co2, vpd),
        iabs       = (ppfd * fapar),
        kphio      = kphio,
        method_jmaxlim_inst = method_jmaxlim_inst,
        maximize   = TRUE
    )
}


p1 <- ggplot(df_2d) + aes(vcmax, cost_vcmax) + geom_point() + ylim(500, 2000)
p2 <- ggplot(df_2d) + aes(jmax, cost_jmax)   + geom_point() + ylim(500, 2000)
p3 <- ggplot(df_2d) + aes(gs, cost_gs)       + geom_point() + ylim(500, 2000)
p4 <- ggplot(df_2d) + aes(jmax, cost_jmax)   + geom_point() + ylim(700, 800)

p1 + p2 + p3 + p4
```

# Testzone

## Changing shape of env output
```{r}
rpmodel_env_response <- function(df_ref   = "no_input",
                                 settings = "no_input",
                                 targets  = "no_input",
                                 drivers  = "no_input",
                                 remove_non_convergence = F,
                                 scales_to_one          = T,
                                 p_output = "per-target"){
    
    ## Input Check ####
    ## Environmental setup
    if (df_ref == "no_input") {
        df_ref <- tibble(tc        = 25,
                         tc_home   = 20,
                         vpd       = 1000,
                         co2       = 400,
                         ppfd      = 1500e-6,
                         patm      = 101325,
                         nsteps    = 50)
    }
    
    
    ## rpmodel setup
    if (settings == "no_input") {settings <- get_settings()}
    if (targets == "no_input") {targets   <- c("chi", "vcmax", "jmax", "gs", "a_gross")} # , "vcmax25", "jmax25"
    if (drivers == "no_input") {drivers   <- c("tc", "vpd", "co2", "ppfd", "patm")}
    
    
    ## Tibble building ####
    ## Environmental setup
    df_ana <- bind_rows(list =
                           tibble(
                               tc = seq(from = 0, to = 40, length.out = df_ref$nsteps),
                               tc_home   = rep(df_ref$tc_home, df_ref$nsteps),
                               vpd       = rep(df_ref$vpd, df_ref$nsteps),
                               co2       = rep(df_ref$co2, df_ref$nsteps),
                               ppfd      = rep(df_ref$ppfd, df_ref$nsteps),
                               patm      = rep(df_ref$patm, df_ref$nsteps),
                               env_var   = "tc"),
                       tibble(
                               tc        = rep(df_ref$tc, df_ref$nsteps),
                               tc_home   = seq(from = 0, to = 40, length.out = df_ref$nsteps),
                               vpd       = rep(df_ref$vpd, df_ref$nsteps),
                               co2       = rep(df_ref$co2, df_ref$nsteps),
                               ppfd      = rep(df_ref$ppfd, df_ref$nsteps),
                               patm      = rep(df_ref$patm, df_ref$nsteps),
                               env_var   = "tc_home"),
                       tibble(
                               tc        = rep(df_ref$tc, df_ref$nsteps),
                               tc_home   = rep(df_ref$tc_home, df_ref$nsteps),
                               vpd       = seq(from = 200, to = 2000, length.out = df_ref$nsteps),
                               co2       = rep(df_ref$co2, df_ref$nsteps),
                               ppfd      = rep(df_ref$ppfd, df_ref$nsteps),
                               patm      = rep(df_ref$patm, df_ref$nsteps),
                               env_var   = "vpd"),
                       tibble(
                               tc        = rep(df_ref$tc, df_ref$nsteps),
                               tc_home   = rep(df_ref$tc_home, df_ref$nsteps),
                               vpd       = rep(df_ref$vpd, df_ref$nsteps),
                               co2       = seq(from = 200, to = 1000, length.out = df_ref$nsteps),
                               ppfd      = rep(df_ref$ppfd, df_ref$nsteps),
                               patm      = rep(df_ref$patm, df_ref$nsteps),
                               env_var   = "co2"),
                       tibble(
                               tc        = rep(df_ref$tc, df_ref$nsteps),
                               tc_home   = rep(df_ref$tc_home, df_ref$nsteps),
                               vpd       = rep(df_ref$vpd, df_ref$nsteps),
                               co2       = rep(df_ref$co2, df_ref$nsteps),
                               ppfd      = seq(from = 100e-6, to = 3000e-6, length.out = df_ref$nsteps),
                               patm      = rep(df_ref$patm, df_ref$nsteps),
                               env_var   = "ppfd"),
                       tibble(
                               tc        = rep(df_ref$tc, df_ref$nsteps),
                               tc_home   = rep(df_ref$tc_home, df_ref$nsteps),
                               vpd       = rep(df_ref$vpd, df_ref$nsteps),
                               co2       = rep(df_ref$co2, df_ref$nsteps),
                               ppfd      = rep(df_ref$ppfd, df_ref$nsteps),
                               patm      = seq(from = calc_patm(4000), to = calc_patm(0), length.out = df_ref$nsteps),
                               env_var   = "patm"))
    
    
    ## Doubling tibble to compare analytical vs. numerical setup
    df_num       <- df_ana
    df_ana$setup <- "analytical"
    df_num$setup <- "numerical"
    df_full      <- bind_rows(list(df_ana, df_num))
    
    
    ## Running rpmodel ####
    for (row in 1:nrow(df_full)) {
        message('\014')
        message("Testing environmental response... ", round(row / nrow(df_full) * 100), " %")
        
        if (df_full$setup[row] == "analytical") {settings$rpmodel_accl$method_optim <- "analytical"}
        if (df_full$setup[row] == "numerical") {settings$rpmodel_accl$method_optim <- "numerical"}
        
        df_loop <- rpmodel(
          
          ## Acclimated inputs
          tc_growth_air = df_full$tc[row],
          tc_home       = df_full$tc_home[row],
          vpd           = df_full$vpd[row],
          co2           = df_full$co2[row],
          ppfd          = df_full$ppfd[row],
          patm          = df_full$patm[row],
          
          ## Local parameters
          kphio         = settings$rpmodel_accl$kphio_calib,
          apar_soilm    = settings$rpmodel_accl$apar_soilm_calib,
          bpar_soilm    = settings$rpmodel_accl$bpar_soilm_calib,
          
          ## Calculation methods
          method_optim   = settings$rpmodel_accl$method_optim, 
          method_jmaxlim = settings$rpmodel_accl$method_jmaxlim,
          method_ftemp   = settings$rpmodel_accl$method_ftemp,
          method_eb      = settings$rpmodel_accl$method_eb
          )
        
        ## Definition of rpmodel output
        df_full$chi[row]     <- df_loop$chi
        df_full$ci[row]      <- df_loop$ci
        df_full$xi[row]      <- df_loop$xi
        df_full$gs[row]      <- df_loop$gs
        df_full$vcmax[row]   <- df_loop$vcmax
        df_full$vcmax25[row] <- df_loop$vcmax25
        df_full$jmax[row]    <- df_loop$jmax
        df_full$jmax25[row]  <- df_loop$jmax25
        df_full$kphio[row]   <- df_loop$kphio
        df_full$a_gross[row] <- df_loop$a_gross
        df_full$tc_growth_leaf[row]   <- df_loop$tc_growth_leaf
        df_full$opt_convergence[row]   <- df_loop$opt_convergence
    }
    
    ## Wrangling tibble for plotting
    df_temp <- df_full %>%
        mutate(env_var = as.factor(env_var),
               setup = as.factor(setup),
               setup = fct_relevel(setup, "numerical", "analytical"))
    
    if (remove_non_convergence) {
        df_temp <- df_temp %>% dplyr::filter(opt_convergence == 0 | is.na(opt_convergence))
        }
    

    ## Generating plots ####
    ## Create empty list
    p_all <- list()
    
    
    ## Loop and append plots
    
    if (p_output == "per-driver") {
        for (t in targets) {
            
            ## Plotting
            p_append <- df_temp %>%
                pivot_longer(cols = all_of(drivers), names_to = "driver", values_to = "driver_value") %>%
                pivot_longer(cols = all_of(t), names_to = "targets", values_to = "targets_value") %>% 
                dplyr::filter(targets == t,
                              driver  == env_var) %>%
                ggplot() +
                aes(x = driver_value, y = targets_value, color = setup, linetype = setup) +
                geom_vline(data = df_ref %>% pivot_longer(cols = all_of(drivers), names_to = "driver", values_to = "x"),
                           aes(xintercept = x),
                           alpha = 0.5, color = "grey50", linetype = "solid", size = 0.5) +
                geom_point(size = 1.5, alpha = 0.8) +
                xlab(paste(" ")) +
                ylab(paste(t)) +
                facet_wrap(~driver, ncol = 3, scales = "free_x") +
                labs(title = paste0("Sensitivity of ", t),
                     caption = paste0("\n Reference conditions (vertical grey lines): \n",
                                      "tc = ", df_ref$tc, " °C",
                                      ", tc_home = ", df_ref$tc_home, " °C",
                                      ", vpd = ", df_ref$vpd, " Pa",
                                      ", co2 = ", df_ref$co2, " ppm",
                                      ", ppfd = ", df_ref$ppfd, " µmol/m2/s",
                                      ", patm = ", df_ref$patm, " Pa")) +
                  theme(plot.caption = element_text(hjust = 0.5, size = 10, lineheight = 1.1),
                        legend.position = c(0.825, 0.25))
            
            ## Fixing scales form comparison
            if ( t == "chi")     {p_append <- p_append + ylim(0.25, 1)}
            if ( t == "vcmax")   {p_append <- p_append + ylim(0, 6e-4)}
            if ( t == "jmax")    {p_append <- p_append + ylim(0, 6e-4)}
            if ( t == "gs")      {p_append <- p_append + ylim(0, 8e-6)}
            if ( t == "a_gross") {p_append <- p_append + ylim(0, 7e-5)}
            
            ## Append plot to list
            p_all[[length(p_all)+1]] <- p_append
            }
        }
        
        
    
    
    ## Define output ####
    out <- list(plot = p_all,
                data = df_full)   
    
    return(out)
}
```


## Function Call
```{r}
## Get reference inputs above

for (i in 1:length(vcmax_v)) {
    for (j in 1:length(jmax_v)) {
        for (k in 1:length(gs_v)) {
            cost_3d[i, j, k] <- optimise_this_tcleaf_vcmax_jmax(
                par        = c(vcmax_v[i], gs_v[k], jmax_v[j]),
                args       = c(tc_leaf, patm, co2, vpd),
                iabs       = (ppfd * fapar),
                kphio      = kphio,
                method_jmaxlim_inst = method_jmaxlim_inst,
                maximize   = TRUE)
        }
    }
}
```

## 3D Plotly
```{r}
## 3D Plot
library(plotly)
# p_v <- list()
# 
# for (k in 1:length(gs_v)) {
#     p <- plot_ly(x = ~vcmax_v, y = ~jmax_v, z = ~cost_3d[,,k]) %>% add_surface()
#     p_v <- list(p_v, p)
# }

plot_ly(x = ~vcmax_v, y = ~jmax_v, z = ~cost_3d[,,10]) %>% add_surface()
plot_ly(x = ~vcmax_v, y = ~gs_v, z = ~cost_3d[,1,]) %>% add_surface()
plot_ly(x = ~jmax_v, y = ~gs_v, z = ~cost_3d[1,,]) %>% add_surface()

plot_ly(x = ~vcmax_v, y = ~jmax_v, z = ~gs_v, color = ~cost_3d[,,k]) %>% add_surface()
plot_ly(z = ~cost_3d[,,1])

## Dev
### Stackoverflow
dat <- data.frame("cat1" = sort(rep(seq(1:6), 6)),
                  "cat2" = rep(seq(1:6), 6),
                  "variable" = round(rnorm(36), 1),
                  "freq" = seq(100, (100-35)))

mat <- tapply(dat$freq, list(dat$cat1, dat$cat2), sum)
mat_col <- tapply(dat$variable, list(dat$cat1, dat$cat2), sum)

plot_ly(z = ~ mat, type = "surface", surfacecolor = mat_col)

### 
plot_ly(z=~mat, type="surface", surfacecolor = matrix(nrow = 6, ncol = 6, rep(1:6, each = 6)))


```

## GGPLOT 3D
```{r}
### When gs is fixed ...........................................................
df_gs_fix <- tibble(vcmax=NA, jmax=NA, cost=NA)

for (i in 1:length(vcmax_v)) {
    for (j in 1:length(jmax_v)) {
            cost_3d <- optimise_this_tcleaf_vcmax_jmax(
                par        = c(vcmax_v[i], gs_fix, jmax_v[j]),
                args       = c(tc_leaf, patm, co2, vpd),
                iabs       = (ppfd * fapar),
                kphio      = kphio,
                method_jmaxlim_inst = method_jmaxlim_inst,
                maximize   = TRUE)
            
            row <- tibble(vcmax = vcmax_v[i], jmax = jmax_v[j], cost = cost_3d)
            df_gs_fix <- bind_rows(df_gs_fix, row)
    }
}
df_gs_fix %<>% mutate(cost = cost/max(cost, na.rm = T))
p_gs_fix <- ggplot(df_gs_fix) + geom_raster(aes(x = vcmax, y = jmax, fill = cost))

### When jmax is fixed .........................................................
df_jmax_fix <- tibble(vcmax=NA, gs=NA, cost=NA)

for (i in 1:length(vcmax_v)) {
    for (j in 1:length(jmax_v)) {
            cost_3d <- optimise_this_tcleaf_vcmax_jmax(
                par        = c(vcmax_v[i], gs_v[j], jmax_fix),
                args       = c(tc_leaf, patm, co2, vpd),
                iabs       = (ppfd * fapar),
                kphio      = kphio,
                method_jmaxlim_inst = method_jmaxlim_inst,
                maximize   = TRUE)
            
            row <- tibble(vcmax = vcmax_v[i], gs = gs_v[j], cost = cost_3d)
            df_jmax_fix <- bind_rows(df_jmax_fix, row)
    }
}

df_jmax_fix %<>% mutate(cost = cost/max(cost, na.rm = T))
p_jmax_fix <- ggplot(df_jmax_fix) + geom_raster(aes(x = vcmax, y = gs, fill = cost))


### When vcmax is fixed ........................................................
df_vcmax_fix <- tibble(jmax=NA, gs=NA, cost=NA)

for (i in 1:length(vcmax_v)) {
    for (j in 1:length(jmax_v)) {
            cost_3d <- optimise_this_tcleaf_vcmax_jmax(
                par        = c(vcmax_fix, gs_v[j], jmax_v[i]),
                args       = c(tc_leaf, patm, co2, vpd),
                iabs       = (ppfd * fapar),
                kphio      = kphio,
                method_jmaxlim_inst = method_jmaxlim_inst,
                maximize   = TRUE)
            
            row <- tibble(jmax = jmax_v[i], gs = gs_v[j], cost = cost_3d)
            df_vcmax_fix <- bind_rows(df_vcmax_fix, row)
    }
}

df_vcmax_fix %<>% mutate(cost = cost/max(cost, na.rm = T))
p_vcmax_fix <- ggplot(df_vcmax_fix) + geom_raster(aes(x = jmax, y = gs, fill = cost))

p_gs_fix
p_jmax_fix
p_vcmax_fix
```

